name: APIFace
favicon: null
layout_spectrum: 0.56383
typography_spectrum: 0.49562
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6edfc'
    - '#37ab69'
    - '#373737'
    - '#f8b243'
    - '#e73a47'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
